export * from './BoxColor';
export * from './ClickablePicture';
export * from './CreditCard';
export * from './Dice';
export * from './Greetings';
export * from './IdCard';
export * from './LikeButton';
export * from './Random';
export * from './Rating';
